name: Jellyfin CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - run: dotnet --version

  build_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore dependencies
        run: dotnet restore
      - name: Build the project
        run: dotnet build --no-restore --configuration Release

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx"
      - name: List Test Results
        run: ls -R **/TestResults/*.trx
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/TestResults/*.trx'

  merge_coverage_results:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - uses: actions/checkout@v3
      - name: Download Test Results
        uses: actions/download-artifact@v3
        with:
          name: test-results
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.1.10
      - name: List Downloaded Artifacts
        run: ls -R
      - name: Merge coverage results
        run: reportgenerator "-reports:**/coverage.cobertura.xml" "-targetdir:merged/" "-reporttypes:Cobertura"
      - name: Upload Coverage Results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-results
          path: merged/

  sonarqube_scan:
    runs-on: ubuntu-latest
    needs: merge_coverage_results
    steps:
      - uses: actions/checkout@v3
      - name: Run SonarQube scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=my-project-key \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.cs.opencover.reportsPaths=**/coverage.opencover.xml

  publish_artifacts:
    runs-on: ubuntu-latest
    needs: build_project
    steps:
      - uses: actions/checkout@v3
      - name: Publish artifacts
        run: |
          dotnet publish --configuration Release --output ./output
          echo "Artifacts published in ./output"
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./output
