name: Jellyfin CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          lfs: true

  setup_environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - run: dotnet --version

  build_project:
    runs-on: ubuntu-latest
    needs: setup_environment
    steps:
      - uses: actions/checkout@v3
      - name: Restore dependencies
        run: dotnet restore
      - name: Build the project
        run: dotnet build --no-restore --configuration Release

  run_tests:
    runs-on: ubuntu-latest
    needs: build_project
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx"
      - name: List Test Results Directory
        run: ls -R
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/TestResults/*.trx'

  publish_artifacts:
    runs-on: ubuntu-latest
    needs: build_project
    steps:
      - uses: actions/checkout@v3
      - name: Publish artifacts
        run: |
          dotnet publish
