stages:
  - checkout
  - setup
  - build
  - test
  - publish

# Etapa de Checkout do código
checkout:
  stage: checkout
  script:
    - echo "Clonando repositório"
  only:
    - master

# Etapa de Setup do Ambiente (.NET Core)
setup_environment:
  stage: setup
  image: mcr.microsoft.com/dotnet/core/sdk:5.0
  script:
    - echo "Configurando ambiente .NET"
    - dotnet --version
  only:
    - master

# Etapa de Build do Projeto
build_project:
  stage: build
  image: mcr.microsoft.com/dotnet/core/sdk:5.0
  script:
    - echo "Restaurando dependências"
    - dotnet restore
    - echo "Buildando o projeto"
    - dotnet build --no-restore --configuration Release
  only:
    - master

# Etapa de Testes Automatizados
run_tests:
  stage: test
  image: mcr.microsoft.com/dotnet/core/sdk:5.0
  script:
    - echo "Executando testes"
    - dotnet test --no-restore --verbosity normal
  only:
    - master

# Etapa de Publicação de Artefatos
publish_artifacts:
  stage: publish
  image: mcr.microsoft.com/dotnet/core/sdk:5.0
  script:
    - echo "Publicando artefatos"
    - dotnet publish --configuration Release --output ./output
    - echo "Artefatos publicados em ./output"
  artifacts:
    paths:
      - ./output
  only:
    - master
